import test from 'node:test';import assert from 'node:assert/strict';
import {normalizeOffers,freshOffer} from '../packages/core/private-markets';
import {parsePyth} from '../packages/core/pyth';
test('PreStocks research rejects bad identity and prices, and produces watchlist or pass without execution',()=>{const p={contract_address:'PreweJYECqtQwBtpxHL171nL2K6umo692gTm7Q3rpgF',symbol:'OPENAI',name:'OpenAI PreStocks',tokenPrice:101,markPrice:100};const offers=normalizeOffers([p,p,{...p,contract_address:'invalid'},{...p,tokenPrice:NaN}],1000);assert.equal(offers.length,1);assert.equal(offers[0].decision,'WATCHLIST');assert.equal(normalizeOffers([{...p,tokenPrice:150}])[0].decision,'PASS');assert.equal(normalizeOffers([{...p,tokenPrice:20}])[0].decision,'PASS');assert.equal(freshOffer(offers[0],2000),true);assert.equal(freshOffer(offers[0],181000),false);});
test('Pyth uses price exponent and original update time, suppressing closed or stale comparisons',()=>{const now=1800000000000;const feeds=[{priceFeedId:922,price:'20000000',exponent:-5,confidence:'1000',feedUpdateTimestamp:now*1000,marketSession:'regular'},{priceFeedId:1792,price:'20200000000',exponent:-8,confidence:'1000000',feedUpdateTimestamp:now*1000,marketSession:'regular'}];const result=parsePyth({parsed:{priceFeeds:feeds}},now);assert.equal(result.status,'fresh');assert.ok(Math.abs(result.premiumPct!-1)<1e-10);assert.equal(parsePyth({parsed:{priceFeeds:feeds}},now+61000).premiumPct,null);assert.equal(parsePyth({parsed:{priceFeeds:[{...feeds[0],marketSession:'closed'},feeds[1]]}},now).premiumPct,null);assert.equal(parsePyth({parsed:{priceFeeds:[feeds[0]]}},now).status,'unavailable');});
import {Audience} from '../packages/core/audience';import {pickTokenPair,finiteValue,quoteMarketValue} from '../packages/core/board';
test('stock quoted launch derives USD valuation without treating stock units as dollars',()=>{const value=quoteMarketValue('0.00000001264',750,1e9);assert.ok(Math.abs(value.priceUsd-.00000948)<1e-15);assert.ok(Math.abs(value.marketCapUsd-9480)<1e-8);for(const input of [null,'bad',0,-1])assert.throws(()=>quoteMarketValue(input,750,1e9));assert.throws(()=>quoteMarketValue('1',NaN,1e9));});
test('gallery rejects spam and updates one vote instead of inflating the total',()=>{let time=1000;const a=new Audience(()=>time);assert.equal(a.vote('viewer','back').total,1);assert.throws(()=>a.vote('viewer','chaos'),/30 seconds/);time+=31000;const changed=a.vote('viewer','doubt');assert.equal(changed.total,1);assert.equal(changed.counts.back,0);assert.equal(changed.counts.doubt,1);assert.throws(()=>a.vote('another','buy'),/listed reaction/);time+=900001;assert.equal(a.snapshot().total,0);});
test('market board selects the exact base mint on Solana by liquidity',()=>{const pairs=[{chainId:'ethereum',baseToken:{address:'mint'},priceUsd:'3',liquidity:{usd:9999}},{chainId:'solana',baseToken:{address:'fake'},priceUsd:'3',liquidity:{usd:9999}},{chainId:'solana',baseToken:{address:'mint'},priceUsd:'2',liquidity:{usd:100},marketCap:500},{chainId:'solana',baseToken:{address:'mint'},priceUsd:'3',liquidity:{usd:500},fdv:10000}];const selected=pickTokenPair(pairs,'mint');assert.equal(selected.priceUsd,'3');assert.equal(finiteValue(selected.marketCap),null,'FDV must not be substituted for market cap');assert.equal(finiteValue(NaN),null);assert.equal(pickTokenPair(pairs,'unknown'),null);});
