import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {generateKeyPairSync} from 'node:crypto';import {address} from '@solana/addresses';import bs58 from 'bs58';
function keypair(){const {privateKey,publicKey}=generateKeyPairSync('ed25519');const pub=publicKey.export({type:'spki',format:'der'}).subarray(-32);return {publicKey:bs58.encode(pub),secretKey:Buffer.concat([privateKey.export({type:'pkcs8',format:'der'}).subarray(-32),pub])};}
import {buyingBudget,buySize,LIMITS,SOL,STOCKS,TOKEN_PROGRAMS} from '../packages/live/config';
import {checkSimulation,validateQuote,loadSigner,type Intent} from '../packages/live/executor';
import {LiveEngine} from '../packages/live/engine';import {freshPrice} from '../packages/live/market';
const owner=keypair().publicKey;
const intent:Intent={deskId:'nvda',side:'BUY',mint:STOCKS[0].mint,amount:'10000000',decimals:8,solPrice:100,tokenPrice:100,at:Date.now()};
const quote=()=>({router:'metis',taker:owner,inputMint:SOL,outputMint:intent.mint,inAmount:intent.amount,outAmount:'1000000',otherAmountThreshold:'995000',swapMode:'ExactIn',transaction:'encoded',requestId:'test',slippageBps:50,priceImpact:.1,signatureFeeLamports:5000,prioritizationFeeLamports:5000,rentFeeLamports:2039280,feeBps:10,lastValidBlockHeight:'12345'});
test('whole-wallet budget grows with claims while preserving fees and per-trade limits',()=>{assert.equal(buyingBudget(1e9),970000000);assert.equal(buyingBudget(2e9),1970000000);assert.equal(buyingBudget(1),0);assert.equal(buySize(1e9,100,0,100),30000000);assert.equal(buySize(1e9,100,15,100),0);assert.equal(buySize(30000000,100,0,100),0);assert.throws(()=>buyingBudget(NaN));});
test('issuer mint allowlist is unique and contains only valid Solana addresses',()=>{assert.equal(new Set(STOCKS.map(s=>s.mint)).size,12);for(const s of STOCKS)assert.equal(address(s.mint),s.mint);assert.equal(STOCKS.find(s=>s.deskId==='spcx')?.symbol,'COINx');});
test('quote rejects wrong mint, owner, excessive costs, stale prices and oversized trades',()=>{validateQuote(quote(),intent,owner,intent.at);for(const change of [{outputMint:SOL},{taker:keypair().publicKey},{slippageBps:500},{priceImpact:2},{rentFeeLamports:9000000},{outAmount:'1'},{otherAmountThreshold:'0'},{router:'jupiterz'},{feeBps:100}])assert.throws(()=>validateQuote({...quote(),...change},intent,owner,intent.at));assert.throws(()=>validateQuote(quote(),intent,owner,intent.at+31000));assert.throws(()=>validateQuote(quote(),{...intent,amount:'1000000000'},owner,intent.at));});
function token(amount:bigint){const raw=Buffer.alloc(165);Buffer.from(bs58.decode(intent.mint)).copy(raw);Buffer.from(bs58.decode(owner)).copy(raw,32);raw.writeBigUInt64LE(amount,64);raw[108]=1;return {owner:TOKEN_PROGRAMS[0],lamports:2039280,data:[raw.toString('base64'),'base64']};}
const native=(lamports:number)=>({owner:'11111111111111111111111111111111',lamports,data:['','base64'],executable:false});
test('transaction simulation accepts expected output and rejects SOL drain, hidden token spends and delegation',()=>{
 const before=[native(1e9),token(100n)],after=[native(987950000),token(1000100n)];checkSimulation(before,after,intent,995000n,owner);
 assert.throws(()=>checkSimulation(before,[native(1000),after[1]],intent,995000n,owner));
 assert.throws(()=>checkSimulation(before,[after[0],token(0n)],intent,995000n,owner));
 const delegated=token(1000100n),raw=Buffer.from(delegated.data[0],'base64');raw.writeUInt32LE(1,72);delegated.data[0]=raw.toString('base64');assert.throws(()=>checkSimulation(before,[after[0],delegated],intent,995000n,owner));
 assert.throws(()=>checkSimulation(before,[after[0],null],intent,995000n,owner));
});
test('stale or missing price cannot qualify for execution',()=>{assert.equal(freshPrice(undefined,1000),false);assert.equal(freshPrice({usdPrice:100,decimals:8,blockId:100},1000),false);assert.equal(freshPrice({usdPrice:100,decimals:8,blockId:999},1000),true);});
test('signer refuses a key for another wallet',()=>{const saved=process.env.TRADING_PRIVATE_KEY;try{process.env.TRADING_PRIVATE_KEY=JSON.stringify([...keypair().secretKey]);assert.throws(()=>loadSigner(owner),/does not match/);}finally{if(saved===undefined)delete process.env.TRADING_PRIVATE_KEY;else process.env.TRADING_PRIVATE_KEY=saved;}});
test('funding accounting, persistence and wallet-change protection',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'floor-live-test-'));const saved={...process.env};process.env.DATA_DIR=dir;process.env.CREATOR_WALLET=owner;process.env.DATA_MODE='shadow';
 try{const e=await LiveEngine.open();const prices=Object.fromEntries([SOL,...STOCKS.map(s=>s.mint)].map(m=>[m,{usdPrice:100,decimals:8,blockId:1000}]));
 const wallet={lamports:1e9,holdings:[],slot:1000};(e as any).account(wallet,prices);assert.equal(e.state.nav,100);assert.equal(e.state.treasury!.pnlUsd,0);
 (e as any).account({...wallet,lamports:2e9},prices);assert.equal(e.state.nav,200);assert.equal(e.state.treasury!.netFundingUsd,200);assert.equal(e.state.treasury!.pnlUsd,0);
 (e as any).account({...wallet,lamports:2e9},{...prices,[SOL]:{...prices[SOL],usdPrice:110}});assert.equal(e.state.treasury!.pnlUsd,20);
 await (e as any).persist();const restored=await LiveEngine.open();assert.equal(restored.state.treasury!.pnlUsd,20);assert.equal(restored.state.mode,'shadow');
 process.env.CREATOR_WALLET=keypair().publicKey;await assert.rejects(()=>LiveEngine.open(),/does not match/);
 }finally{process.env=saved;await rm(dir,{recursive:true,force:true});}
});
test('unresolved saved transaction survives restart and cannot be submitted twice',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'floor-pending-test-'));const saved={...process.env},fetchSaved=globalThis.fetch;process.env.DATA_DIR=dir;process.env.CREATOR_WALLET=owner;process.env.DATA_MODE='shadow';
 try{const e=await LiveEngine.open();(e as any).journal.pending={intent,signature:'pending-signature',lastValidBlockHeight:12345,submittedAt:Date.now()};await (e as any).persist();let calls:string[]=[];
 globalThis.fetch=async(_url,options)=>{const method=JSON.parse(options!.body as string).method;calls.push(method);return Response.json({result:method==='getTransaction'?null:method==='getSignatureStatuses'?{value:[null]}:12000});};process.env.RPC_URL='https://rpc.test';
 const restored=await LiveEngine.open();await restored.cycle();assert.deepEqual(calls,['getTransaction','getSignatureStatuses','getBlockHeight']);const disk=JSON.parse(await readFile(join(dir,'trading-shadow.json'),'utf8'));assert.equal(disk.pending.signature,'pending-signature');assert.equal(restored.state.tickets.length,0);
 }finally{globalThis.fetch=fetchSaved;process.env=saved;await rm(dir,{recursive:true,force:true});}
});
import {createPublicKey,verify} from 'node:crypto';
test('signing uses the matching ed25519 key and signs the exact message',()=>{const keys=keypair(),saved=process.env.TRADING_PRIVATE_KEY;try{process.env.TRADING_PRIVATE_KEY=bs58.encode(keys.secretKey);const signer=loadSigner(keys.publicKey),message=Buffer.from('test transaction message');const signature=signer.sign(message);const publicKey=createPublicKey({key:Buffer.concat([Buffer.from('302a300506032b6570032100','hex'),Buffer.from(bs58.decode(keys.publicKey))]),type:'spki',format:'der'});assert.equal(verify(null,message,publicKey,signature),true);assert.equal(verify(null,Buffer.from('other transaction'),publicKey,signature),false);}finally{if(saved===undefined)delete process.env.TRADING_PRIVATE_KEY;else process.env.TRADING_PRIVATE_KEY=saved;}});
test('scaled stock balances increase NAV without inventing a deposit',async()=>{const dir=await mkdtemp(join(tmpdir(),'floor-scaled-test-')),saved={...process.env};process.env.DATA_DIR=dir;process.env.CREATOR_WALLET=owner;process.env.DATA_MODE='shadow';try{const e=await LiveEngine.open(),prices=Object.fromEntries([SOL,...STOCKS.map(s=>s.mint)].map(m=>[m,{usdPrice:100,decimals:8,blockId:1000,multiplier:1}]));const w={lamports:1e9,holdings:[{mint:STOCKS[0].mint,amount:'100000000',decimals:8}],slot:1000};(e as any).account(w,prices);assert.equal(e.state.nav,200);(e as any).account(w,{...prices,[STOCKS[0].mint]:{...prices[STOCKS[0].mint],multiplier:1.1}});assert.equal(e.state.desks[0].qty,1.1);assert.equal(e.state.treasury!.netFundingUsd,200);assert.equal(e.state.treasury!.pnlUsd,10);}finally{process.env=saved;await rm(dir,{recursive:true,force:true});}});
test('finalized swap reconciliation counts fees as loss, not funding, exactly once',async()=>{const dir=await mkdtemp(join(tmpdir(),'floor-fill-test-')),saved={...process.env},originalFetch=globalThis.fetch;process.env.DATA_DIR=dir;process.env.CREATOR_WALLET=owner;process.env.DATA_MODE='shadow';process.env.RPC_URL='https://rpc.test';try{const e=await LiveEngine.open(),prices=Object.fromEntries([SOL,...STOCKS.map(s=>s.mint)].map(m=>[m,{usdPrice:100,decimals:8,blockId:1000}]));(e as any).account({lamports:1e9,holdings:[],slot:1000},prices);(e as any).journal.pending={intent,signature:'receipt',lastValidBlockHeight:1234,submittedAt:Date.now()};globalThis.fetch=async()=>Response.json({result:{slot:1000,transaction:{message:{accountKeys:[owner]}},meta:{err:null,preBalances:[1e9],postBalances:[987000000],preTokenBalances:[],postTokenBalances:[{owner,mint:intent.mint,uiTokenAmount:{amount:'1000000',decimals:8}}]}}});await (e as any).settle();(e as any).account({lamports:987000000,holdings:[{mint:intent.mint,amount:'1000000',decimals:8}],slot:1000},prices);assert.equal(e.state.tickets.length,1);assert.equal(e.state.tickets[0].signature,'receipt');assert.equal(e.state.treasury!.netFundingUsd,100);assert.ok(Math.abs(e.state.treasury!.pnlUsd+.3)<1e-8);await (e as any).settle();assert.equal(e.state.tickets.length,1);assert.equal((e as any).journal.receipts.length,1);}finally{globalThis.fetch=originalFetch;process.env=saved;await rm(dir,{recursive:true,force:true});}});
