'use client';
import {useEffect,useState} from 'react';
import {useFloor} from './store';
import type {Reaction} from '@/packages/core/audience';
export function useBoardData(){useEffect(()=>{let closed=false;const controllers=new Set<AbortController>();async function read(path:string,key:'setBoard'|'setAudience'){const c=new AbortController();controllers.add(c);try{const r=await fetch(path,{signal:c.signal});if(!r.ok)throw Error();const data=await r.json();if(!closed)useFloor.getState()[key](data);}catch{}finally{controllers.delete(c);}}
 void read('/api/board','setBoard');void read('/api/audience','setAudience');
 const board=setInterval(()=>{if(!document.hidden)void read('/api/board','setBoard');},15000),audience=setInterval(()=>{if(!document.hidden)void read('/api/audience','setAudience');},5000);
 return()=>{closed=true;clearInterval(board);clearInterval(audience);for(const c of controllers)c.abort();};},[]);}
const usd=(v:number|null|undefined)=>v==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(v);
const sol=(v:number|null|undefined)=>v==null?'—':v.toLocaleString('en-US',{maximumFractionDigits:4})+' SOL';
function age(at:number|null|undefined,now:number){return at?now-at>90000?'STALE · '+Math.floor((now-at)/60000)+'m ago':'READ '+Math.max(0,Math.floor((now-at)/1000))+'s AGO':'NOT CONNECTED';}
export function CompanyBoard(){const b=useFloor(s=>s.board),[now,setNow]=useState(Date.now());useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),5000);return()=>clearInterval(t);},[]);return <section className="company-board" aria-label="Public token and wallet board">
 <div className="board-heading"><span className="eyebrow">THE PUBLIC BOARD</span><b>{b?.mode==='project'?'THE FLOOR':'TEST CONNECTIONS'}</b><small>{b?.mode==='project'?'Token market data':'Sample token + sample wallet'}</small></div>
 <div className="board-number"><label>TOKEN MARKET CAP <span>{b?.token.symbol??''}</span></label><strong>{usd(b?.token.marketCapUsd)}</strong><small>{age(b?.token.at,now)} · DEX SCREENER</small>{b?.token.error&&<em>{b.token.error}</em>}</div>
 <div className="board-number"><label>CREATOR / TREASURY WALLET</label><strong>{sol(b?.wallet.sol)}</strong><small>{age(b?.wallet.balanceAt,now)} · SOLANA</small>{b?.wallet.address&&<a href={'https://solscan.io/account/'+b.wallet.address} target="_blank" rel="noreferrer">VIEW WALLET ↗</a>}</div>
 <div className="board-number"><label>DIRECT CREATOR FEES <span title={b?.wallet.feeScope}>ⓘ</span></label><strong>{sol(b?.wallet.feesSol)}</strong><small>{age(b?.wallet.feesAt,now)} · UNCLAIMED ESTIMATE</small>{b?.wallet.error&&<em>{b.wallet.error}</em>}</div>
 <details className="board-details"><summary>What these numbers mean ↗</summary><p>Token market cap is token price × reported circulating supply. It is not company valuation, wallet cash, or a claim on the treasury. The test token and wallet are independent examples.</p><p>{b?.wallet.feeScope??'Direct creator-vault reads only.'} No automatic claims or transfers.</p>{b?.token.mint&&<a target="_blank" rel="noreferrer" href={'https://dexscreener.com/solana/'+(b.token.pair??b.token.mint)}>Inspect token data ↗</a>}<p>The office trades a fictional $500 bankroll for entertainment. Its simulated profits are not treasury funds.</p></details>
 </section>;}
export function Gallery(){const audience=useFloor(s=>s.audience),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[until,setUntil]=useState(0),[now,setNow]=useState(Date.now());useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[]);
 async function react(reaction:Reaction){setBusy(true);try{const r=await fetch('/api/audience',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reaction})});const data=await r.json();if(!r.ok)throw Error(data.error);useFloor.getState().setAudience(data);setUntil(Date.now()+30000);setMessage('The principal heard you. Your reaction influences the next story.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="gallery"><div className="panel-heading"><span>THE GALLERY</span><span>{audience.total} RECENT VOICES</span></div><h2>The boss is listening.</h2><p>Feed their egos. Question their competence. Start something.</p><div className="gallery-buttons">{(['back','doubt','chaos'] as const).map((v,i)=><button key={v} disabled={busy||now<until} onClick={()=>void react(v)}><span>{['↗','↘','⚡'][i]}</span>{['Back the floor','Doubt the boss','More chaos'][i]}<b>{audience.counts[v]}</b></button>)}</div><p role="status" className="gallery-status">{now<until?'Next reaction in '+Math.ceil((until-now)/1000)+'s. '+message:message}</p><small>Public reactions · Last 15 minutes · One per viewer<br/>Reactions influence upcoming office stories. Anonymous participation; no wallet required.</small></section>;
}
export function OfficeBoard(){const show=useFloor(s=>s.show);const b=useFloor(s=>s.board),a=useFloor(s=>s.audience);const fresh=!!b?.token.at&&Date.now()-b.token.at<90000;return <div className="office-board"><div><b>THE FLOOR / PUBLIC TAPE</b><span>{b?.mode==='project'?'TOKEN':'TEST TOKEN'}</span></div><strong>{show?.kind==='outage'?'OFFLINE':usd(b?.token.marketCapUsd)}</strong><span>{show?.kind==='outage'?'FICTIONAL IT OUTAGE · ':''}TOKEN MARKET CAP {fresh?'':'· UNAVAILABLE / STALE'}</span><footer>{a.total?'GALLERY: '+a.counts.back+' BACK / '+a.counts.doubt+' DOUBT / '+a.counts.chaos+' CHAOS':'THE GALLERY IS WATCHING'}</footer></div>;}
