'use client';
import {CompanyBoard,Gallery,useBoardData} from './Board';
import PrivateMarketsPanel from './PrivateMarkets';
import {CutawayDirector,startCutaway,cutawayClock} from './CutawayDirector';
import ShowDirector from './ShowDirector';
import {ShowCaption,ShowControls,OfficeStories,ShowPreviews} from './ShowUI';
import ContractAddress from './ContractAddress';
import dynamic from 'next/dynamic';import {FloorSound} from './sound';import {useEffect,useRef,useState} from 'react';import {useFloor} from './store';import type {Desk,FloorEvent} from '@/packages/core/types';
const Scene=dynamic(()=>import('./Scene'),{ssr:false,loading:()=> <div className="scene-loading">Setting out the desks…</div>});
const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v);
const time=(v:number)=>new Date(v).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});
function Spark({values}:{values:number[]}){const min=Math.min(...values)-.1,max=Math.max(...values)+.1;return <svg viewBox="0 0 240 44" preserveAspectRatio="none" aria-label="Treasury NAV history"><path d={values.map((v,i)=>(i?'L':'M')+(i/Math.max(1,values.length-1)*240)+','+(40-(v-min)/(max-min)*36)).join(' ')} fill="none" stroke="currentColor" strokeWidth="2"/></svg>;}
function Dossier({desk}:{desk:Desk}){const s=useFloor(x=>x.snapshot)!;const resolved=desk.forecasts.filter(f=>f.actual!==undefined);return <>
 <div className="panel-heading"><span>PERSONNEL FILE / {String(desk.seed+1).padStart(2,'0')}</span><button onClick={()=>useFloor.getState().select(null)} aria-label="Close analyst dossier">×</button></div>
 <div className="identity"><div className="monogram" style={{background:desk.color}}>{desk.name.split(' ').map(n=>n[0]).join('')}</div><div><h2>{desk.name}</h2><p>{desk.symbol} desk <span>· {desk.traits.focus.replace('_',' ')}</span></p></div></div>
 <div className="trait-row"><span>{desk.traits.temperament}</span><span>Risk {desk.traits.risk}/10</span><span>Session {desk.hiredSession} hire</span></div>
 <div className="dossier-metrics"><div><label>POSITION</label><strong>{money(desk.qty*desk.price)}</strong><small>{desk.qty.toFixed(4)} units</small></div><div><label>DESK P&L</label><strong className={desk.realized+desk.qty*desk.price-desk.cost>=0?'positive':'negative'}>{money(desk.realized+desk.qty*desk.price-desk.cost)}</strong><small>Realized + unrealized</small></div></div>
 <div className="record"><span>FORECAST RECORD</span><b>{resolved.length?Math.round(resolved.filter(f=>f.hit).length/resolved.length*100)+'%':'—'} <small>directional accuracy</small></b><p>{resolved.length} resolved · {desk.pitches.length} pitches · {desk.pitches.filter(p=>p.violations.length).length} risk blocks</p></div>
 <h3>At the desk <span>THESIS HISTORY</span></h3>
 <div className="theses">{desk.pitches.length?desk.pitches.slice(0,15).map(p=><article key={p.id}><div className="pitch-top"><b>{p.side} {money(p.usd)}</b><span className={p.violations.length?'negative':'positive'}>{p.decision}</span></div><p>{p.thesis}</p><div className="forecast"><span>Target {money(p.forecast.target)}</span><b>{p.forecast.actual!==undefined?(p.forecast.hit?'HIT':'MISS')+' · '+money(p.forecast.actual):Math.max(0,Math.ceil((p.forecast.due-s.now)/60000))+'m remaining'}</b></div><small>{time(p.at)} · Principal: {p.reason}</small></article>):<p className="empty">Research begins on the next market tick. Every forecast and risk decision will be recorded here.</p>}</div>
 </>;}
export default function FloorApp({localControls=false}:{localControls?:boolean}){
 useBoardData();
 const {snapshot:s,selected,connected,event,cutaway,show,showBeat,theater}=useFloor();const [tab,setTab]=useState<'floor'|'ledger'|'people'>('floor');const [entered,setEntered]=useState(false);const [muted,setMuted]=useState(true);const [controls,setControls]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const audio=useRef<FloorSound|null>(null);
 function enableSound(enabled:boolean){if(!audio.current)audio.current=new FloorSound();audio.current.setCutaway(useFloor.getState().cutaway?.phase??'idle',cutawayClock.elapsed);void audio.current.setEnabled(enabled);setMuted(!enabled);}
 useEffect(()=>()=>audio.current?.dispose(),[]);
 useEffect(()=>{if(entered&&tab==='floor'&&!muted&&!s?.paused&&!cutaway)void audio.current?.showBeat(show,showBeat);},[show?.id,showBeat,muted,entered,tab,s?.paused,cutaway?.id]);
 useEffect(()=>{const sync=()=>audio.current?.setCutaway(document.hidden||s?.paused||!entered||tab!=='floor'?'suspended':cutaway?.phase??'idle',cutawayClock.elapsed);sync();document.addEventListener('visibilitychange',sync);return()=>document.removeEventListener('visibilitychange',sync);},[cutaway?.phase,s?.paused,entered,tab]);
 useEffect(()=>{const queue:{event:FloorEvent;ready:number}[]=[];let last=0;let first=true;const es=new EventSource('/api/floor?stream=1');
 es.onmessage=e=>{const state=JSON.parse(e.data);useFloor.getState().setSnapshot(state);if(first){last=state.events.at(-1)?.id??0;first=false;}else for(const ev of state.events){if(ev.id>last){queue.push({event:ev,ready:Date.now()+1500});last=ev.id;}}};
 es.onerror=()=>useFloor.getState().setConnected(false);
 const interval=setInterval(()=>{if(!queue.length||queue[0].ready>Date.now())return;const ev=queue.shift()!.event;useFloor.getState().setEvent(ev);audio.current?.event(ev);},400);
 const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){useFloor.getState().setTheater(false);useFloor.getState().select(null);setControls(false);}};
 const blotter=()=>setTab('ledger');window.addEventListener('keydown',onKey);window.addEventListener('open-blotter',blotter);
 return()=>{es.close();clearInterval(interval);window.removeEventListener('keydown',onKey);window.removeEventListener('open-blotter',blotter);};},[]);
 async function command(action:string){setBusy(true);setError('');try{const r=await fetch('/api/floor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});if(!r.ok)throw Error((await r.json()).error);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const real=s?.mode==='live'||s?.mode==='shadow';
 const desk=s?.desks.find(d=>d.id===selected);
 return <main className={theater?'cinema-mode':''}><ShowDirector enabled={entered&&tab==='floor'}/><CutawayDirector enabled={entered&&tab==='floor'}/>
 <header><a className="brand" href="/" aria-label="The Floor home"><img className="brand-mark" src="/favicon.svg" width="44" height="44" alt=""/><span>THE FLOOR<small>TWELVE EGOS. ONE BALANCE SHEET.</small></span></a><nav aria-label="Views">{(['floor','ledger','people'] as const).map(t=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}>{t==='floor'?'Trading floor':t==='ledger'?'Trade ledger':'Personnel'}</button>)}</nav><div className="header-right"><ContractAddress/><button className="sound" onClick={()=>enableSound(muted)} aria-label={muted?'Enable sound':'Mute sound'}>{muted?'Sound off':'Sound on'} <span>{muted?'◌':'◖'}</span></button></div></header>
 <div className="ticker"><span className="ticker-label">{real?'SOLANA STOCKS':'FICTIONAL TAPE'}</span><div className="ticker-track">{s?.desks.map(d=><button key={d.id} onClick={()=>{useFloor.getState().select(d.id);setTab('floor');}}><b>{d.symbol}</b><span>{money(d.price)}</span><small className={d.change>=0?'positive':'negative'}>{d.change>=0?'+':''}{d.change.toFixed(2)}%</small></button>)}</div></div>
 <section className="summary"><div className="session-label"><span className={'live-dot '+(!connected?'offline':'')}/><div><b>{!connected?'Connecting to the floor':s?.killed?'Execution halted':s?.paused?'Show paused':s?.marketOpen?'The floor is open':'The night shift'}</b><small>SESSION {String(s?.session??1).padStart(3,'0')} <span> / </span> {s?time(s.now):'—'} {real?'LOCAL TIME':'SIM TIME'}</small></div></div><div className="stat"><label>{real?'WALLET PORTFOLIO':'SIMULATED BANKROLL'}</label><strong>{s?money(s.nav):'—'}</strong></div><div className="stat"><label>{real?'NET P&L':'FICTIONAL P&L'}</label><strong className={(s?.nav??500)>=(s?.openNav??500)?'positive':'negative'}>{s?money(s.nav-s.openNav):'—'}</strong></div><div className="stat"><label>{real?'AVAILABLE SOL':'SIMULATED CASH'}</label><strong>{real?s?.treasury?.availableSol.toFixed(4)??'—':s?money(s.cash):'—'}</strong></div><div className="mini-chart"><Spark values={s?.curve.map(p=>p.nav)??[500]}/><span>{real?'P&L · funding excluded':'$500 opening treasury'}</span></div></section>
 {real&&<div className="trading-status"><b>{s?.mode==='live'?(s.treasury?.tradingEnabled?'AUTOMATIC TRADING ON':s.treasury?.testStatus&&['buy','sell'].includes(s.treasury.testStatus)?'TEST ONLY · AUTO OFF':'TRADING STOPPED'):'WALLET PREVIEW · NO EXECUTION'}</b><span>{s?.treasury?.status??'Connecting to treasury…'}</span><span>0.03 SOL fee reserve</span>{s?.treasury&&<a href={'https://solscan.io/account/'+s.treasury.wallet} target="_blank" rel="noreferrer">Treasury on Solscan ↗</a>}{s?.treasury?.pendingSignature&&<a href={'https://solscan.io/tx/'+s.treasury.pendingSignature} target="_blank" rel="noreferrer">Pending transaction ↗</a>}</div>}
 <CompanyBoard/>
 {tab==='floor'?<section className={'floor-layout '+(desk?'with-dossier':'')}>
 <div className={"viewport "+(cutaway?"has-cutaway":"")+(show?" has-show":"")}><div className="room-caption"><span>01 / THE ROOM</span><h1>BIG EGOS.<br/>SMALL MARGINS.</h1><p>{s?.desks.length??12} fictional analysts. One principal.</p></div><Scene/>{entered&&<ShowControls/>}<ShowCaption/>
 <div className="camera-hint">DRAG TO ORBIT <span>·</span> SCROLL TO ZOOM <span>·</span> SELECT A DESK</div>
 {event&&!show&&<div className="bark"><span>{event.deskId?.toUpperCase()??'THE PRINCIPAL'}</span><p>{event.text}</p></div>}
 {!entered&&<div className="entry"><div><span className="eyebrow">WELCOME TO THE FLOOR</span><h2>CLOCK IN.<br/>WATCH IT UNFOLD.</h2><p>Twelve egos. Absolutely no adult supervision.<br/>{real?'Real wallet. Ridiculous office politics.':'Fake money. Real office politics.'}</p><button className="primary" disabled={!connected} onClick={()=>{setEntered(true);enableSound(true);}}>Enter the floor <span>↗</span></button><small>An animated trading-floor comedy · Sound on</small></div></div>}
 </div>
 <aside className="side-panel"><Gallery/><PrivateMarketsPanel/><OfficeStories/>{desk?<Dossier desk={desk}/>:<><div className="panel-heading"><span>THE SQUAWK BOX</span><span className="tiny-badge">FLOOR FEED</span></div><h2>Word on the floor.</h2><p className="panel-intro">Bad forecasts. Big speeches. An alarming amount of coffee.</p><div className="feed">{s?.events.slice(-20).reverse().map(e=><article key={e.id} className={e.kind==='RISK_BLOCK'?'blocked':''}><div><span>{e.deskId?.toUpperCase()??'PRINCIPAL'}</span><time>{time(e.at)}</time></div><p>{e.text}</p><small>{e.kind.replaceAll('_',' ')}</small></article>)}</div><div className="desk-invite"><span>↖</span><p><b>Get to know the desk.</b><br/>Click an analyst to inspect their forecast, position, and track record.</p></div></>}</aside>
 </section>:tab==='ledger'?<section className="table-page"><span className="eyebrow">02 / THE PAPER TRAIL</span><h1>Every fill has a receipt.</h1><p>{real?'Finalized Solana swaps. Every receipt links to the public transaction.':'Fictional trades, faithfully documented. The printer takes this far too seriously.'}</p><div className="tickets">{s?.tickets.length?s.tickets.map(t=><article className="ticket" key={t.id}><div><b>THE FLOOR</b><span>{t.paper?'PAPER':'SOLANA'} / {String(t.id).padStart(5,'0')}</span></div><h2>{t.side} {t.symbol}</h2><strong>{money(t.usd)}</strong><dl><dt>{t.paper?'Fill price':'Net wallet cost / unit'}</dt><dd>{money(t.price)}</dd><dt>Quantity</dt><dd>{t.qty.toFixed(6)}</dd><dt>{t.paper?'Simulated time':'Time'}</dt><dd>{time(t.at)}</dd></dl><footer>{t.signature?<a href={'https://solscan.io/tx/'+t.signature} target="_blank" rel="noreferrer">FINALIZED · View on Solscan ↗</a>:'FICTIONAL TRADE · ENTERTAINMENT ONLY'}</footer><button onClick={()=>{useFloor.getState().select(t.deskId);setTab('floor');}}>Open analyst dossier ↗</button></article>):<p className="empty">The printer is waiting for the first approved fill.</p>}</div></section>:<section className="table-page"><span className="eyebrow">03 / PERSONNEL</span><h1>A seat is earned.</h1><p>{real?'Live scores refresh with fresh market data, about every 15 seconds. 50% trading P&L relative to treasury size, 40% forecast accuracy minus error, 10% discipline. Forecasts resolve after one hour. No automatic dismissals in live mode.':'Two sessions of protection for new hires. Then forecasts and discipline count.'}</p><div className="personnel">{s?.desks.map(d=><button key={d.id} onClick={()=>{useFloor.getState().select(d.id);setTab('floor');}}><span className="person-avatar" style={{background:d.color}}>{d.name.split(' ').map(n=>n[0]).join('')}</span><span><b>{d.name}</b><small>{d.symbol} · {d.traits.temperament}</small></span><span className="score">{real&&!d.scoreAt?'—':d.score.toFixed(3)}<small>{real?(d.scoreAt?'LIVE SCORE':'AWAITING RESULTS'):'LAST SCORE'}</small></span></button>)}</div>{!!s?.archive.length&&<><h2>Former analysts</h2>{s.archive.map(d=><p key={d.analystId}>{d.name} · {d.symbol} · final score {d.score.toFixed(3)} · {d.forecasts.filter(f=>f.actual!==undefined).length} forecasts resolved</p>)}</>}</section>}
 <footer className="bottom-bar"><div><span className="amber-dot"/> {real?'SOLANA STOCKS. OFFICE EGOS.':s?.marketOpen?'THE MARKET IS FICTIONAL. THE EGOS ARE NOT.':'NIGHT SHIFT · SAME EGOS, LESS SUPERVISION'}<span className="footer-divider">/</span> {s?.tickets.length??0} FILLS <span className="footer-divider">/</span> {s?.killed?'RISK HALTED':'OFFICE OPEN'}</div>{localControls&&<button onClick={()=>setControls(!controls)}>Rehearsal controls <span>⌘</span></button>}</footer>
 {localControls&&controls&&<div className="controls"><div className="panel-heading"><span>LOCAL REHEARSAL</span><button onClick={()=>setControls(false)} aria-label="Close controls">×</button></div><p>Preview office stories or control the fictional market.</p><ShowPreviews onStart={()=>{setEntered(true);setTab('floor');setControls(false);}}/><button disabled={busy||!connected} onClick={()=>command('pause')}>{s?.paused?'Resume':'Pause'} simulation</button><button disabled={busy||!connected} onClick={()=>command('night')}>Switch to {s?.marketOpen?'night':'day'} shift</button><button disabled={busy||!connected} onClick={()=>command('risk')}>Test an oversized $500 pitch</button><button disabled={busy||!connected} onClick={()=>command('close')}>Close session & score analysts</button><button disabled={Boolean(cutaway)||Boolean(s?.paused)} onClick={()=>{setEntered(true);setTab('floor');setControls(false);startCutaway();}}>Preview principal cutaway</button><button className="danger" disabled={busy||!connected} onClick={()=>command('kill')}>{s?.killed?'Re-enable':'Halt'} execution</button>{error&&<p role="alert">{error}</p>}</div>}
 <div className="disclosure">{real?'The characters and office stories are fictional. This mode displays the operator’s Solana wallet and tokenized stocks. Only finalized swaps appear as trades; preview mode never submits orders. Portfolio P&L excludes observed funding flows and includes SOL price changes. Unrelated wallet tokens are excluded. Viewers cannot deposit or place trades.':'The Floor is an entertainment simulation. Characters, market prices, trades, and trading profits are fictional. The public token and wallet board uses separate real-world data when configured. No deposits, investment service, or real-money trading.'}</div>
 </main>;
}

