'use client';
import {useEffect,useState} from 'react';
import {useFloor} from './store';
import {startShow} from './ShowDirector';
import {freshOffer,type PrivateMarkets} from '@/packages/core/private-markets';
import type {PythResearch} from '@/packages/core/pyth';
const dollars=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v);
export default function PrivateMarketsPanel(){const data=useFloor(s=>s.privateMarkets),active=useFloor(s=>!!s.show||!!s.cutaway),[pyth,setPyth]=useState<PythResearch|null>(null),[now,setNow]=useState(Date.now());
 useEffect(()=>{let done=false;const controller=new AbortController();async function read(){if(document.hidden)return;setNow(Date.now());await Promise.allSettled([fetch('/api/private-markets',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then((v:PrivateMarkets)=>{if(!done)useFloor.getState().setPrivateMarkets(v);}),fetch('/api/research',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(v=>{if(!done)setPyth(v);})]);}void read();const timer=setInterval(read,30000);return()=>{done=true;controller.abort();clearInterval(timer);};},[]);
 const pythFresh=pyth?.status==='fresh'&&now-pyth.at<60000;
 return <section className="private-markets"><div className="panel-heading"><span>PRIVATE MARKETS</span><span>PRESTOCKS</span></div><h2>Someone has a pitch.</h2><p>Real issuer data. Fictional salesman. Research decisions only.</p>{data?.error&&<p role="status">{data.error}</p>}{!data&&<p>Checking the visitor list…</p>}<div className="private-offers">{data?.offers.map(o=><article key={o.mint}><div><b>{o.name}</b><span className={o.decision==='PASS'?'negative':'positive'}>{o.decision}</span></div><strong>{dollars(o.price)}</strong><small>Reference mark {dollars(o.mark)} · {o.premiumPct>=0?'+':''}{o.premiumPct.toFixed(2)}%</small><p>{o.reason}</p><button disabled={active||!freshOffer(o,now)} onClick={()=>startShow(o.decision==='WATCHLIST'?'private-watch':'private-pass','PreStocks · research only',o)}>Hear the pitch ↗</button><a href={'https://solscan.io/token/'+o.mint} target="_blank" rel="noreferrer">Token ↗</a></article>)}</div><small>Retrieved {data?.at?new Date(data.at).toLocaleTimeString():'—'}. The issuer API does not provide the underlying mark timestamp. A mark is not a guaranteed exit price. No PreStocks purchase is executed by this feature.</small><div className="pyth-research"><div className="panel-heading"><span>THE INDEPENDENT TAPE</span><span>PYTH</span></div><h3>Apple vs. its stock token</h3>{pyth?.points.map(p=><p key={p.symbol}><b>{p.symbol}</b> {dollars(p.price)} <small>{p.session} · price timestamp {new Date(p.at).toLocaleTimeString()}</small></p>)}<strong>{pythFresh&&pyth?.premiumPct!=null?`${pyth.premiumPct>=0?'+':''}${pyth.premiumPct.toFixed(2)}% token premium`:'Comparison unavailable'}</strong><p>{pythFresh?pyth?.reason:pyth?.status==='fresh'?'Waiting for a fresh update.':pyth?.reason??'Checking independent feeds…'}</p><small>Research context only. This panel does not authorize orders or treat closed-market prices as current opportunities.</small></div></section>;
}
