import {createServer} from 'node:net';
import {spawn,execFileSync} from 'node:child_process';import {mkdtemp,readFile,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import assert from 'node:assert/strict';
async function freePort(){const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;await new Promise(r=>server.close(r));return port;}
const webPort=await freePort(),workerPort=await freePort();
const data=await mkdtemp(join(tmpdir(),'floor-deploy-'));let child;let logs='';const base='http://127.0.0.1:'+webPort;
async function start(){child=spawn(process.execPath,['scripts/start.mjs'],{env:{...process.env,PORT:String(webPort),WORKER_PORT:String(workerPort),DATA_DIR:data,ALLOW_LOCAL_CONTROLS:'0',RPC_URL:'',TOKEN_MINT:'',CREATOR_WALLET:'',AUDIENCE_SECRET:'isolated-deployment-check-only'},stdio:['ignore','pipe','pipe'],windowsHide:true});child.stdout.on('data',c=>{logs+=c;});child.stderr.on('data',c=>{logs+=c;});for(let i=0;i<60;i++){try{if((await fetch(base+'/api/health')).ok)return;}catch{}await new Promise(r=>setTimeout(r,500));}throw Error('Startup failed: '+logs.slice(-2000));}
async function stop(){if(!child)return;if(process.platform==='win32'){try{execFileSync('taskkill',['/PID',String(child.pid),'/T','/F'],{stdio:'ignore',windowsHide:true});}catch{}}else{child.kill('SIGTERM');await new Promise(r=>child.once('exit',r));}child=null;}
try{await start();const html=await (await fetch(base)).text();assert.ok(!html.includes('Rehearsal controls'));
const forbidden=await fetch(base+'/api/floor',{method:'POST',headers:{origin:base,'Content-Type':'application/json'},body:'{"action":"kill"}'});assert.equal(forbidden.status,403);
const foreign=await fetch(base+'/api/audience',{method:'POST',headers:{origin:'https://unrelated.example','Content-Type':'application/json'},body:'{"reaction":"chaos"}'});assert.equal(foreign.status,403);
const vote=await fetch(base+'/api/audience',{method:'POST',headers:{origin:base,'Content-Type':'application/json'},body:'{"reaction":"back"}'});assert.equal(vote.status,200);const cookie=vote.headers.get('set-cookie').split(';')[0];assert.equal((await vote.json()).counts.back,1);
const repeat=await fetch(base+'/api/audience',{method:'POST',headers:{origin:base,cookie,'Content-Type':'application/json'},body:'{"reaction":"doubt"}'});assert.equal(repeat.status,429);
await new Promise(r=>setTimeout(r,5600));const saved=JSON.parse(await readFile(join(data,'snapshot.json'),'utf8'));await stop();await start();const restored=await (await fetch(base+'/api/floor')).json();assert.ok(restored.now>=saved.now);assert.equal(restored.session,saved.session);
const board=await (await fetch(base+'/api/board')).json();assert.equal(board.token.marketCapUsd,null);assert.equal(board.wallet.sol,null);
await writeFile('reports/deployment-check.json',JSON.stringify({passed:true,checks:['supervised startup','health','public controls denied','cross-origin vote denied','vote cookie cooldown','persistent restart','unconfigured data stays null']},null,2));console.log('Deployment and public-control checks passed');}finally{await stop();}
