import {writeFile} from 'node:fs/promises';
const cast=[
['nvda','Nvidia',[
'These chips are paying for somebody’s yacht. Not mine yet.','Stop drawing arrows on my Nvidia chart.','I need a second opinion, not a second sandwich.','Can somebody explain this candle without waving their arms?','My screen has more green than the office plant.','I have three models and four different answers.','The semiconductor desk would like some breathing room.','That is a thesis. Your coffee stain is not a thesis.','If this phone rings again, I am billing the phone.','Nobody touch my lucky calculator.','I have been staring at this chip chart since breakfast.','The server is hot and so is my patience.','Someone tell the boss this is a research process.','The chart moved while I was explaining the chart.','I need the latest volume, not yesterday’s gossip.','Who put a sticky note over my risk numbers?']],
['spy','S and P',[
'The benchmark desk would like everyone to take a breath.','Five hundred companies and somehow this room is louder.','You cannot diversify away your personality.','I am comparing returns, not decibel levels.','Can we have one opinion supported by arithmetic?','The index does not care about your lucky tie.','That is the market. Your stock is a small part of it.','I brought the benchmark. Who brought the perspective?','Everyone is a genius until we subtract the index.','The broad market desk requests a quieter telephone.','If you need me, I will be counting calmly.','There is an entire economy outside your monitor.','Please stop using my desk as a podium.','I would like my spreadsheet back in one piece.','Your chart is dramatic. My chart is useful.','One number at a time, people.']],
['tsla','Tesla',[
'The Tesla desk has consumed all the emergency coffee.','I looked away for one second. One second!','My chair is moving less than this chart.','Who installed the panic button next to the calculator?','I am perfectly calm. Where is my other phone?','Somebody lower the volume on that candlestick.','This desk needs seat belts.','I have revised my opinion and also my lunch plans.','Do not confuse my hand gestures with a buy signal.','The Tesla desk would like to file a noise complaint against itself.','I need a quote and possibly a walk.','Stop saying relax while pointing at my screen.','My risk assessment has several exclamation marks.','The coffee is decaf? That explains absolutely nothing.','Who moved my stress ball to the risk desk?','I am not pacing. I am gathering information.']],
['crcl','Circle',[
'The Circle desk is accepting facts, preferably fresh ones.','Stablecoin plumbing is not glamorous, but somebody has to watch it.','You cannot settle an argument with a louder keyboard.','I said liquidity, not liquid lunch.','Somebody trace that flow before naming it a trend.','I want the actual quote, not an enthusiastic approximation.','This is a cash-flow conversation. Please stop singing.','The spread deserves a second look.','I have found a discrepancy and misplaced my pen.','Who borrowed the Circle desk’s charging cable?','If it is so obvious, put it in the forecast.','The story is interesting. Now show me the numbers.','My monitor has fingerprints from three different arguments.','I would enjoy one meeting without the word moon.','Give me thirty seconds and an unbroken pencil.','Settlement waits for nobody. Neither does this phone.']],
['aapl','Apple',[
'The Apple desk has heard this story before.','New headline, same spreadsheet.','I prefer my forecasts with fewer fireworks.','Is that a catalyst or just a very expensive rumor?','Someone has confused a product launch with a trading plan.','Put the shiny phone down and read the numbers.','I am waiting for a price, not applause.','If the thesis fits on a sticker, check it again.','This desk runs on skepticism and black coffee.','Everybody loves a story. I would like a margin.','The Apple desk is not taking fashion advice.','You cannot swipe away the risk limit.','I am rechecking the reference price. Again.','That presentation had more gradients than evidence.','Please stop naming chart patterns after your lunch.','I have one question. Unfortunately it is about valuation.']],
['qqq','Nasdaq',[
'The Nasdaq desk is counting the same names everyone is yelling about.','Congratulations, you have rediscovered concentration risk.','Technology is the theme. Arithmetic is the method.','Someone turn down the optimism on monitor two.','I want the basket, not the loudest ingredient.','How many of those positions are secretly the same trade?','The sector map is not a personality test.','I need one clean data feed and two minutes.','Your diversification appears to be wearing three different hats.','The Nasdaq desk has a question about your assumptions.','Stop dragging windows across my benchmark chart.','We are discussing exposure, not screen brightness.','That correlation did not vanish because you stopped looking.','I have a spreadsheet for that argument.','Can somebody answer the phone without announcing it?','The weightings are small print for a reason. Read them.']],
['mstr','Micro Strategy',[
'The Micro Strategy desk requests stronger coffee and weaker opinions.','Two charts, one headache.','Before you shout, tell me which exposure you mean.','That premium is not a rounding error.','I have been awake since the first confusing headline.','Someone has put a rocket sticker on my risk sheet.','This thesis has layers. Most of them are noisy.','Can we separate the company from the thing it holds?','I asked for a scenario, not a prophecy.','Nobody is allowed to say guaranteed at this desk.','The Micro Strategy phone has developed a nervous habit.','I am checking the premium before checking my messages.','Put the bullhorn down. Pick the calculator up.','That is leverage wearing a nicer jacket.','If you quote me, include the entire sentence.','The market has questions. So does my accountant.']],
['spcx','Space X',[
'The Space X desk is watching the spread, not the launch pad.','A countdown is not an investment thesis.','I need a reference price that exists on this planet.','Please stop making rocket noises behind my chair.','The premium has my attention. The headline can wait.','Someone has stapled a moon drawing to the order form.','We are measuring liquidity, not altitude.','I would like a quieter orbit around this desk.','The space jokes are now officially over budget.','Your enthusiasm appears to have escaped the atmosphere.','Can we land this discussion on an actual number?','The Space X desk requests fewer metaphors.','A tiny quote is not proof of a deep market.','Let me finish checking the route.','Mission control has asked for your source.','I have a launch window for my lunch break.']],
['meta','Meta',[
'The Meta desk has muted this argument in three different tabs.','Engagement is high. Evidence is still pending.','That headline has been shared more than it has been read.','I am researching the company, not your group chat.','The comments section is not a data source.','Who changed my spreadsheet to dark mode?','I want the flow behind the story.','You cannot like your way out of a bad entry.','This desk has too many open windows and not enough air.','Somebody is pitching a narrative with no numbers attached.','We are all aware of the headline. What changed?','I have hidden the rocket emoji column.','That is a popular opinion. Is it a useful one?','The Meta desk will respond after verifying the claim.','Stop tagging me in your price targets.','My phone is vibrating itself toward the edge.']],
['amzn','Amazon',[
'The Amazon desk has ordered a replacement for this conversation.','Delivery estimate for your evidence: still pending.','I would like to return this unsupported assumption.','Margins first. Dramatic hand gestures second.','Someone stacked trade slips where my lunch used to be.','That is a very large business and a very small sample.','The cloud numbers are not hiding behind the retail numbers.','I need the full basket of facts.','Please do not put another package on my keyboard.','I am comparing segments, not shopping for narratives.','Your forecast arrived without instructions.','The Amazon desk has a question about the cost base.','We have same-day delivery and last-week data. Wonderful.','I put that rumor in the returns pile.','The printer has become our busiest employee.','Can somebody sign for this spreadsheet?']],
['goog','Google',[
'The Google desk found six answers and trusts two of them.','I have searched the entire room for a quiet opinion.','Your source appears to be somebody repeating your source.','The first result is not automatically the right result.','I am following the revenue, not the slogan.','Who left seventeen browser tabs on my machine?','That claim needs a date and a denominator.','I would like the underlying numbers before the summary.','Search says maybe. The spreadsheet says check again.','The Google desk is currently fact-checking the room.','I did not ask the printer for a second opinion.','We have enough keywords. We need a conclusion.','Someone has bookmarked the wrong chart again.','That is an excellent question with a suspiciously fast answer.','Please stop calling every small move a revolution.','I found the missing number. It was under your coffee.']],
['msft','Microsoft',[
'The Microsoft desk has saved this argument as version twelve.','Your thesis has unsaved changes.','I need the cloud figures, not a cloud of hand waving.','Someone has turned my risk sheet into a presentation.','We are one spreadsheet away from a civilized office.','The model works. The assumptions would like a word.','Please stop restarting the conversation.','I have highlighted the part everyone keeps skipping.','This desk is installing a patience update.','The Microsoft phone is requesting administrator approval.','If your forecast crashes, do not blame the keyboard.','Can we agree which version of the number we are using?','That is a recurring revenue story, not a recurring excuse.','I would like to close six unnecessary meetings.','The formula is correct. Your input is a coffee stain.','I am saving before anybody touches anything.']]
];
const categories={
pitch:[
'I have a proposal on {ticker}. Hear me out.','Boss, the {ticker} case is on your desk.','Let me make the {ticker} argument before you say no.','The {ticker} forecast is written down. Your call.','I want a hearing for this {ticker} position.','There is a {ticker} setup worth discussing.'],
approved:[
'{ticker} has approval. Checking the order details.','Got the nod on {ticker}. Keep the paperwork straight.','The boss said yes to {ticker}. Stay disciplined.','Approved on {ticker}. Nobody improvise the size.','Permission through on {ticker}. Watch the quote.','The {ticker} allocation cleared the boss. Now the checks.'],
trim:[
'Half a sandwich and a trimmed {ticker} allocation. Great.','You cut the {ticker} size? I had a whole speech ready.','Fine, smaller {ticker} position. Same thesis.','The {ticker} budget just got a haircut.','Trimmed on {ticker}. I heard you the first time.','The boss likes {ticker}, apparently in miniature.'],
risk:[
'No order on {ticker}. Risk has the last word.','The {ticker} ticket hit a hard limit.','Risk blocked {ticker}. Put the enthusiasm away.','The {ticker} request failed the checks. Read the reason.','That {ticker} order is not going anywhere.','Rejected by risk on {ticker}. Back to the desk.'],
fill:[
'{ticker} filled. Get that receipt out.','Paper fill on {ticker}. Check the quantity.','The {ticker} ticket is through. Record the price.','That is our {ticker} fill. Keep the receipt.','Print it. The {ticker} paper order filled.','{ticker} is in the ledger. Somebody mind the printer.'],
hit:[
'The {ticker} forecast hit. It is in the record.','Right direction on {ticker}. Check the timestamp.','One forecast point for the {ticker} desk.','I got the {ticker} direction. Do not lose that page.','The {ticker} call held up at the deadline.','Score the {ticker} forecast. This one was right.'],
miss:[
'The {ticker} forecast missed. Leave it on the record.','Wrong direction on {ticker}. I am rechecking the thesis.','The {ticker} desk owes the spreadsheet an apology.','That {ticker} call did not hold up. No excuses.','Mark the miss on {ticker}. We keep those too.','I was wrong on {ticker}. Let me find the assumption.'],
night:[
'The cash market is closed. I am watching the token spread.','Reference is last close. Do not call that a live stock price.','Night shift again. At least the phones are quiet.','Frozen reference, moving token. Label the difference.'],
challenge:[
'Would you defend that forecast without the hand gestures?','That is confidence. Where is the evidence?','Did you check the benchmark before raising your voice?','Can the next person bring numbers instead of volume?'],
reply:[
'The assumptions are written down. You are welcome to read them.','I have the numbers. Let me finish the sentence.','The forecast is on record. We will both see the result.','You can challenge the model after I explain the model.']
};
const boss=[
'One at a time. I can only reject so many ideas at once.','Enough theater. Bring me the numbers.','Keep the aisle clear and the cash reserve intact.','You are all very confident with my spreadsheet.','Nobody gets a larger limit by shouting.','I want competing theses, not competing ringtones.','The risk desk is not an obstacle course.','Somebody answer that phone before I reassign it.','Put it in writing. Then argue about it.','We run one treasury. Remember the word one.','Take a breath. Check the quote. Then talk.','The loudest desk is not automatically the best desk.','I need a decision, a size, and a reason.','Who put a coffee cup on the session report?','We are not holding a shouting competition. Yet.','If the printer jams, we still keep the ledger.','I can hear the confidence. I cannot hear the evidence.','No victory speeches before the forecast resolves.','Your next sentence should contain a number.','Back to your desks. We have work to do.'
];
const script={};
for(const [id,ticker,ambient] of cast){
 script[id]=ambient.map((text,i)=>({text,category:'ambient',key:id+'-ambient-'+i}));
 for(const [category,lines] of Object.entries(categories))lines.forEach((line,i)=>script[id].push({text:line.replaceAll('{ticker}',ticker),category,key:category+'-'+i}));
}
script.principal=boss.map((text,i)=>({text,category:'boss',key:'boss-'+i}));
await writeFile('scripts/voice-script.json',JSON.stringify(script,null,2));
const all=Object.values(script).flat();console.log({clips:all.length,uniqueSpokenLines:new Set(all.map(l=>l.text)).size,distinctLinePatterns:new Set(all.map(l=>l.key)).size});

