import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
await mkdir('reports',{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[],requests=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.url().includes('/vo/show/'))requests.push({url:r.url(),status:r.status()});});
await p.goto('http://localhost:3100');await p.getByRole('button',{name:'Enter the floor'}).click();
async function controls(){await p.getByRole('button',{name:'Rehearsal controls'}).click();}
async function end(){await controls();if(await p.getByRole('button',{name:'End current story',exact:true}).isEnabled())await p.getByRole('button',{name:'End current story',exact:true}).click();}
const kinds=['printer','victory','blame','audit','outage','phones','coffee','speech'];const titles=['THE PRINTER HAS POSITIONED ITSELF','A VERY PREMATURE VICTORY LAP','THE BLAME TRANSFER DESK','COMPLIANCE HAS ENTERED THE CHAT','IT HAS LEFT THE BUILDING','EVERYONE IS ON HOLD','A LIQUIDITY CRISIS','MANDATORY OPTIONAL MOTIVATION'];
const samples=[];
for(let i=0;i<kinds.length;i++){
 await end();await p.getByRole('button',{name:titles[i]+' ↗',exact:true}).click();await p.waitForFunction(kind=>window.__floorShow?.kind===kind,kinds[i]);await p.waitForFunction(()=>window.__floorShow?.beat>=2);await p.waitForTimeout(350);
 assert.ok((await p.locator('.show-subtitle p').textContent()).length>5);await p.screenshot({path:'reports/show-'+kinds[i]+'.png'});const data=await p.evaluate(()=>({show:window.__floorShow,audio:window.__floorAudio,metrics:window.__floorMetrics}));samples.push(data);console.log('SCENE',kinds[i],JSON.stringify({beat:data.show.beat,fps:data.metrics.fps,drawCalls:data.metrics.drawCalls,errors:data.audio.failures}));assert.equal(data.audio.failures,0);
 if(i===0){await p.waitForFunction(()=>!window.__floorShow?.kind);assert.ok(await p.locator('.office-stories article').count());}
}
await p.getByRole('button',{name:'Cinema view'}).click();assert.ok(await p.locator('main.cinema-mode').count());await p.screenshot({path:'reports/show-cinema.png'});await p.keyboard.press('Escape');assert.equal(await p.locator('main.cinema-mode').count(),0);
await p.getByRole('button',{name:'Trade ledger',exact:true}).click();await p.waitForTimeout(200);const paused=await p.evaluate(()=>window.__floorShow.elapsed);await p.waitForTimeout(1100);assert.equal(await p.evaluate(()=>window.__floorShow.elapsed),paused);await p.getByRole('button',{name:'Trading floor',exact:true}).click();
await p.setViewportSize({width:390,height:844});await p.waitForTimeout(900);await p.screenshot({path:'reports/show-mobile.png',fullPage:true});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await end();await p.getByRole('button',{name:'THE PRINTER HAS POSITIONED ITSELF ↗',exact:true}).click();await p.waitForTimeout(600);await controls();await p.getByRole('button',{name:'Preview principal cutaway'}).click();await p.waitForTimeout(500);assert.equal(await p.evaluate(()=>window.__floorShow.kind),null);
assert.equal(errors.length,0,errors.join('\n'));assert.ok(requests.length>=40);assert.ok(requests.every(r=>r.status===200));await writeFile('reports/show-check.json',JSON.stringify({errors,requests,samples},null,2));await b.close();console.log('PASS: eight stories, audio, completion, cinema, pause, mobile, cutaway priority');
